const visitorTypes = [
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Want a burger?',
		 name: 'Mr Tentacles',
		 stateMultiplier:1.12,
		 tierMultiplier:1.05,
		 typeMultiplier:1.35,
		 weighting:15,
		 statePreferred: {name: 'noState', value: 9},
		 tierPreferred: {name: 'mithril', value: 4},
		 typePreferred: {name: 'dessert', value: 27},
		 visitorID:51,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'I\'s got all these coins but nuffin good. Whatchu got?',
		 name: 'Bresh Bosh',
		 stateMultiplier:1.2,
		 tierMultiplier:1.39,
		 typeMultiplier:1.14,
		 weighting:9,
		 statePreferred: {name: 'Red Enchant', value: 3},
		 tierPreferred: {name: 'rune', value: 6},
		 typePreferred: {name: 'gloves', value: 14},
		 visitorID:52,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Here to spread Easter joy!',
		 name: 'Easter Bunny',
		 stateMultiplier:1.24,
		 tierMultiplier:1.24,
		 typeMultiplier:1.24,
		 weighting:40,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'none', value: 11},
		 typePreferred: {name: 'dessert', value: 27},
		 visitorID:53,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'I love my brother!',
		 name: 'Blinky',
		 stateMultiplier:1.16,
		 tierMultiplier:1.15,
		 typeMultiplier:1.07,
		 weighting:6,
		 statePreferred: {name: 'Red Enchant', value: 3},
		 tierPreferred: {name: 'dragon', value: 7},
		 typePreferred: {name: 'hammer', value: 18},
		 visitorID:54,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'I hate my brother!',
		 name: 'Sparky',
		 stateMultiplier:1.16,
		 tierMultiplier:1.15,
		 typeMultiplier:1.07,
		 weighting:6,
		 statePreferred: {name: 'Blue Enchant', value: 4},
		 tierPreferred: {name: 'dragon', value: 7},
		 typePreferred: {name: 'hammer', value: 18},
		 visitorID:55,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'I like unfinished things, they burn better!',
		 name: 'Senor Spicy Hot',
		 stateMultiplier:3.0,
		 tierMultiplier:1.1,
		 typeMultiplier:1.1,
		 weighting:3,
		 statePreferred: {name: 'Unfinished', value: 2},
		 tierPreferred: {name: 'bronze', value: 1},
		 typePreferred: {name: 'gloves', value: 14},
		 visitorID:1,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'If only I was a woodcutter...',
		 name: 'Mister Hatchet',
		 stateMultiplier:1.2,
		 tierMultiplier:1.2,
		 typeMultiplier:1.2,
		 weighting:6,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'steel', value: 3},
		 typePreferred: {name: 'hatchet', value: 16},
		 visitorID:2,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'It\'s not rubbish, it\'s treasure!',
		 name: 'Lord of the Junk',
		 stateMultiplier:1.05,
		 tierMultiplier:1.05,
		 typeMultiplier:1.05,
		 weighting:10,
		 statePreferred: {name: 'Unfinished', value: 2},
		 tierPreferred: {name: 'bronze', value: 1},
		 typePreferred: {name: 'dagger', value: 3},
		 visitorID:3,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Only the best for me, old chap.',
		 name: 'Monsieur Fancypants',
		 stateMultiplier:1.5,
		 tierMultiplier:1.6,
		 typeMultiplier:1.55,
		 weighting:1,
		 statePreferred: {name: 'Blue Enchant', value: 4},
		 tierPreferred: {name: 'premium', value: 10},
		 typePreferred: {name: 'plateBody', value: 10},
		 visitorID:4,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Me hungry. Tummy rumbling.',
		 name: 'Grumbling Rock',
		 stateMultiplier:1.05,
		 tierMultiplier:1.05,
		 typeMultiplier:1.4,
		 weighting:5,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'none', value: 11},
		 typePreferred: {name: 'ore', value: 1},
		 visitorID:5,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Me very hungry. Tummy rumbling loud.',
		 name: 'Large Grumbling Rock',
		 stateMultiplier:1.05,
		 tierMultiplier:1.6,
		 typeMultiplier:1.8,
		 weighting:1,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'none', value: 11},
		 typePreferred: {name: 'ore', value: 1},
		 visitorID:6,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'They say I\'m the short-tempered one, but I just like the colour.',
		 name: 'R. De Couleur',
		 stateMultiplier:1.66,
		 tierMultiplier:1.25,
		 typeMultiplier:1.05,
		 weighting:2,
		 statePreferred: {name: 'Red Enchant', value: 3},
		 tierPreferred: {name: 'dragon', value: 7},
		 typePreferred: {name: 'gem', value: 20},
		 visitorID:7,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'They say I\'m the jealous one, but I just like the colour.',
		 name: 'G. De Couleur',
		 stateMultiplier:1.66,
		 tierMultiplier:1.25,
		 typeMultiplier:1.05,
		 weighting:2,
		 statePreferred: {name: 'Blue Enchant', value: 4},
		 tierPreferred: {name: 'adamant', value: 5},
		 typePreferred: {name: 'gem', value: 20},
		 visitorID:8,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'They say I\'m the unhappy one, but I just like the colour.',
		 name: 'B. De Couleur',
		 stateMultiplier:1.66,
		 tierMultiplier:1.25,
		 typeMultiplier:1.05,
		 weighting:2,
		 statePreferred: {name: 'Green Enchant', value: 5},
		 tierPreferred: {name: 'rune', value: 6},
		 typePreferred: {name: 'gem', value: 20},
		 visitorID:9,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'They say I\'m the scared one, but I just like the colour.',
		 name: 'W. De Couleur',
		 stateMultiplier:1.66,
		 tierMultiplier:1.25,
		 typeMultiplier:1.05,
		 weighting:1,
		 statePreferred: {name: 'White Enchant', value: 6},
		 tierPreferred: {name: 'silver', value: 8},
		 typePreferred: {name: 'gem', value: 20},
		 visitorID:10,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'They say I\'m the scary one, but I just like the colour.',
		 name: 'B. De Couleur',
		 stateMultiplier:1.66,
		 tierMultiplier:1.25,
		 typeMultiplier:1.05,
		 weighting:1,
		 statePreferred: {name: 'Black Enchant', value: 7},
		 tierPreferred: {name: 'none', value: 20},
		 typePreferred: {name: 'gem', value: 20},
		 visitorID:11,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'So what if I\'m not quite in shape?',
		 name: 'Gelatinous Egg',
		 stateMultiplier:1.1,
		 tierMultiplier:1.05,
		 typeMultiplier:1.15,
		 weighting:8,
		 statePreferred: {name: 'Unfinished', value: 2},
		 tierPreferred: {name: 'none', value: 11},
		 typePreferred: {name: 'additionalIngredient', value: 19},
		 visitorID:12,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'You there! Got any of the yellow stuff?',
		 name: 'The Great Cheese Menace',
		 stateMultiplier:1.05,
		 tierMultiplier:1.05,
		 typeMultiplier:1.55,
		 weighting:6,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'none', value: 11},
		 typePreferred: {name: 'foodIngredient', value: 21},
		 visitorID:13,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Slurp, slurp.',
		 name: 'The Leech King',
		 stateMultiplier:1.25,
		 tierMultiplier:1.25,
		 typeMultiplier:1.25,
		 weighting:3,
		 statePreferred: {name: 'Black Enchant', value: 7},
		 tierPreferred: {name: 'dragon', value: 7},
		 typePreferred: {name: 'sword', value: 4},
		 visitorID:14,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Do you like my outfit?',
		 name: 'Man of Magicka',
		 stateMultiplier:1.05,
		 tierMultiplier:1.05,
		 typeMultiplier:1.05,
		 weighting:7,
		 statePreferred: {name: 'Black Enchant', value: 7},
		 tierPreferred: {name: 'none', value: 11},
		 typePreferred: {name: 'gloves', value: 14},
		 visitorID:15,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Give me your rare items, I\'ll look after them!',
		 name: 'Rare Chest',
		 stateMultiplier:1.04,
		 tierMultiplier:1.1,
		 typeMultiplier:1.02,
		 weighting:1,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'adamant', value: 5},
		 typePreferred: {name: 'foodIngredient', value: 21},
		 visitorID:16,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Give me your items, I\'ll look after them!',
		 name: 'Chest',
		 stateMultiplier:1.04,
		 tierMultiplier:1.1,
		 typeMultiplier:1.01,
		 weighting:4,
		 statePreferred: {name: 'Unfinished', value: 2},
		 tierPreferred: {name: 'mithril', value: 4},
		 typePreferred: {name: 'foodIngredient', value: 21},
		 visitorID:17,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Don\'t worry, it\'s a coloured contact lens.',
		 name: 'Eye of Ender',
		 stateMultiplier:1.3,
		 tierMultiplier:1.3,
		 typeMultiplier:1.3,
		 weighting:1,
		 statePreferred: {name: 'White Enchant', value: 6},
		 tierPreferred: {name: 'rune', value: 6},
		 typePreferred: {name: 'fullHelmet', value: 12},
		 visitorID:18,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'BRAINS',
		 name: 'BRAINS',
		 stateMultiplier:1.15,
		 tierMultiplier:1.1,
		 typeMultiplier:1.15,
		 weighting:6,
		 statePreferred: {name: 'Green Enchant', value: 5},
		 tierPreferred: {name: 'bronze', value: 1},
		 typePreferred: {name: 'fullHelmet', value: 12},
		 visitorID:19,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Seen Obelix anywhere?',
		 name: 'Asterisk The Ghoul',
		 stateMultiplier:1.05,
		 tierMultiplier:1.05,
		 typeMultiplier:1.1,
		 weighting:3,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'bronze', value: 1},
		 typePreferred: {name: 'hatchet', value: 16},
		 visitorID:20,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'I don\'t suppose you\'ve got any monocles?',
		 name: 'Eye of Starter',
		 stateMultiplier:1.2,
		 tierMultiplier:1.2,
		 typeMultiplier:1.2,
		 weighting:4,
		 statePreferred: {name: 'White Enchant', value: 6},
		 tierPreferred: {name: 'steel', value: 3},
		 typePreferred: {name: 'halfHelmet', value: 11},
		 visitorID:21,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'I\'ve got shoes on.',
		 name: 'Marcell',
		 stateMultiplier:1.01,
		 tierMultiplier:1.01,
		 typeMultiplier:1.01,
		 weighting:5,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'none', value: 11},
		 typePreferred: {name: 'additionalIngredient', value: 19},
		 visitorID:22,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Snippy, snippy!',
		 name: 'Crabby',
		 stateMultiplier:1.02,
		 tierMultiplier:1.02,
		 typeMultiplier:1.02,
		 weighting:3,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'none', value: 11},
		 typePreferred: {name: 'dagger', value: 3},
		 visitorID:23,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'From down south. No, REALLY south. REAAALLLY south.',
		 name: 'Southerner',
		 stateMultiplier:1.1,
		 tierMultiplier:1.15,
		 typeMultiplier:1.15,
		 weighting:2,
		 statePreferred: {name: 'Red Enchant', value: 3},
		 tierPreferred: {name: 'dragon', value: 7},
		 typePreferred: {name: 'bow', value: 6},
		 visitorID:24,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'No nibbling.',
		 name: 'Magical Mushroom',
		 stateMultiplier:1.05,
		 tierMultiplier:1.01,
		 typeMultiplier:1.15,
		 weighting:5,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'none', value: 11},
		 typePreferred: {name: 'foodIngredient', value: 21},
		 visitorID:25,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'You know I can sting repeatedly, right?',
		 name: 'Overwasp',
		 stateMultiplier:1.05,
		 tierMultiplier:1.25,
		 typeMultiplier:1.15,
		 weighting:4,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'gold', value: 9},
		 typePreferred: {name: 'sword', value: 4},
		 visitorID:26,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Seen Asterisk anywhere?',
		 name: 'Obelix The Ghoul',
		 stateMultiplier:1.05,
		 tierMultiplier:1.05,
		 typeMultiplier:1.1,
		 weighting:3,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'bronze', value: 1},
		 typePreferred: {name: 'hatchet', value: 16},
		 visitorID:27,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Don\'t tell Steve, but his secret mine isn\'t so secret.',
		 name: 'Whippersnappette',
		 stateMultiplier:1.05,
		 tierMultiplier:1.05,
		 typeMultiplier:1.15,
		 weighting:5,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'adamant', value: 5},
		 typePreferred: {name: 'pickaxe', value: 15},
		 visitorID:28,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'I wish my hair wasn\'t so exposed to the elements.',
		 name: 'Hatty',
		 stateMultiplier:1.05,
		 tierMultiplier:1.08,
		 typeMultiplier:1.15,
		 weighting:5,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'none', value: 11},
		 typePreferred: {name: 'fullHelmet', value: 12},
		 visitorID:29,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'It\'s all about the bullseye.',
		 name: 'Archer',
		 stateMultiplier:1.15,
		 tierMultiplier:1.1,
		 typeMultiplier:1.25,
		 weighting:2,
		 statePreferred: {name: 'Green Enchant', value: 5},
		 tierPreferred: {name: 'iron', value: 2},
		 typePreferred: {name: 'bow', value: 6},
		 visitorID:30,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Gotta dig deeper and deeper and deeper and...',
		 name: 'Steve',
		 stateMultiplier:1.05,
		 tierMultiplier:1.05,
		 typeMultiplier:1.15,
		 weighting:6,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'rune', value: 6},
		 typePreferred: {name: 'pickaxe', value: 15},
		 visitorID:31,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Don\'t tell Steve, but his secret fish pond isn\'t so secret.',
		 name: 'Whippersnapper',
		 stateMultiplier:1.02,
		 tierMultiplier:1.05,
		 typeMultiplier:1.2,
		 weighting:6,
		 statePreferred: {name: 'Blue Enchant', value: 4},
		 tierPreferred: {name: 'none', value: 11},
		 typePreferred: {name: 'fishingRod', value: 17},
		 visitorID:32,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Need a hand?',
		 name: 'Mr T Utorial',
		 stateMultiplier:1.05,
		 tierMultiplier:1.05,
		 typeMultiplier:1.05,
		 weighting:1,
		 statePreferred: {name: 'Blue Enchant', value: 4},
		 tierPreferred: {name: 'bronze', value: 1},
		 typePreferred: {name: 'ore', value: 1},
		 visitorID:33,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Ssscared of sssnakesss?',
		 name: 'Sammy the Snake',
		 stateMultiplier:1.05,
		 tierMultiplier:1.1,
		 typeMultiplier:1.15,
		 weighting:9,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'steel', value: 3},
		 typePreferred: {name: 'bow', value: 6},
		 visitorID:34,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'I am all powerful. Okay, apart from equipment. Shh.',
		 name: 'Power Orb',
		 stateMultiplier:1.09,
		 tierMultiplier:1.03,
		 typeMultiplier:1.12,
		 weighting:7,
		 statePreferred: {name: 'Blue Enchant', value: 4},
		 tierPreferred: {name: 'rune', value: 6},
		 typePreferred: {name: 'ore', value: 1},
		 visitorID:35,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Is it hot in here?',
		 name: 'Frankie Fire',
		 stateMultiplier:1.2,
		 tierMultiplier:1.08,
		 typeMultiplier:1.15,
		 weighting:7,
		 statePreferred: {name: 'Red Enchant', value: 3},
		 tierPreferred: {name: 'premium', value: 10},
		 typePreferred: {name: 'visage', value: 23},
		 visitorID:36,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'I.. can.. barely.. move.',
		 name: 'Emerald Giant',
		 stateMultiplier:1.16,
		 tierMultiplier:1.16,
		 typeMultiplier:1.08,
		 weighting:6,
		 statePreferred: {name: 'Green Enchant', value: 5},
		 tierPreferred: {name: 'adamant', value: 5},
		 typePreferred: {name: 'sword', value: 4},
		 visitorID:37,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'BZZ.. GIVE SILVER. PLZ.',
		 name: 'PURPLEBOT9000',
		 stateMultiplier:1.01,
		 tierMultiplier:1.19,
		 typeMultiplier:1.11,
		 weighting:5,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'silver', value: 8},
		 typePreferred: {name: 'ring', value: 24},
		 visitorID:38,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'I\'m a little bit dizzy. Actually, very dizzy.',
		 name: 'Whirling Dervish',
		 stateMultiplier:1.12,
		 tierMultiplier:1.1,
		 typeMultiplier:1.02,
		 weighting:5,
		 statePreferred: {name: 'Blue Enchant', value: 4},
		 tierPreferred: {name: 'rune', value: 6},
		 typePreferred: {name: 'bar', value: 2},
		 visitorID:39,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Sure is cold up there.',
		 name: 'Stumps',
		 stateMultiplier:1.03,
		 tierMultiplier:1.04,
		 typeMultiplier:1.12,
		 weighting:9,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'none', value: 11},
		 typePreferred: {name: 'boots', value: 13},
		 visitorID:40,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'I am a completely normal human. Completely normal.',
		 name: 'Octomum',
		 stateMultiplier:1.08,
		 tierMultiplier:1.18,
		 typeMultiplier:1.13,
		 weighting:3,
		 statePreferred: {name: 'Blue Enchant', value: 4},
		 tierPreferred: {name: 'mithril', value: 4},
		 typePreferred: {name: 'gloves', value: 14},
		 visitorID:41,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Make it quick, I\'ve got somewhere to be.',
		 name: 'Battletoad',
		 stateMultiplier:1.07,
		 tierMultiplier:1.08,
		 typeMultiplier:1.2,
		 weighting:1,
		 statePreferred: {name: 'Green Enchant', value: 5},
		 tierPreferred: {name: 'adamant', value: 5},
		 typePreferred: {name: 'fishingRod', value: 17},
		 visitorID:42,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'I hope I\'m not scaring you. I\'m so sorry if I am. Sorry.',
		 name: 'Casper',
		 stateMultiplier:1.09,
		 tierMultiplier:1.08,
		 typeMultiplier:1.11,
		 weighting:4,
		 statePreferred: {name: 'White Enchant', value: 6},
		 tierPreferred: {name: 'silver', value: 8},
		 typePreferred: {name: 'gemPowder', value: 22},
		 visitorID:43,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'I am more than a mere mummy, I am Mummioso!',
		 name: 'Mummioso',
		 stateMultiplier:1.04,
		 tierMultiplier:1.02,
		 typeMultiplier:1.12,
		 weighting:4,
		 statePreferred: {name: 'White Enchant', value: 6},
		 tierPreferred: {name: 'none', value: 11},
		 typePreferred: {name: 'plateBody', value: 10},
		 visitorID:44,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'It\'s not even a scratch!',
		 name: 'The Black Knight',
		 stateMultiplier:1.15,
		 tierMultiplier:1.1,
		 typeMultiplier:1.14,
		 weighting:4,
		 statePreferred: {name: 'Black Enchant', value: 7},
		 tierPreferred: {name: 'iron', value: 2},
		 typePreferred: {name: 'longSword', value: 5},
		 visitorID:45,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Hello! Oh, also BRAINS.',
		 name: 'Mrs BRAINS',
		 stateMultiplier:1.16,
		 tierMultiplier:1.11,
		 typeMultiplier:1.16,
		 weighting:1,
		 statePreferred: {name: 'Green Enchant', value: 5},
		 tierPreferred: {name: 'bronze', value: 1},
		 typePreferred: {name: 'fullHelmet', value: 12},
		 visitorID:46,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'My bark is as good as my bite.',
		 name: 'Sir Stumps',
		 stateMultiplier:1.04,
		 tierMultiplier:1.05,
		 typeMultiplier:1.13,
		 weighting:1,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'none', value: 11},
		 typePreferred: {name: 'boots', value: 13},
		 visitorID:47,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'You there! Got any of the yeasty stuff?',
		 name: 'The Great Bread Menace',
		 stateMultiplier:1.05,
		 tierMultiplier:1.05,
		 typeMultiplier:1.55,
		 weighting:1,
		 statePreferred: {name: 'Normal', value: 1},
		 tierPreferred: {name: 'none', value: 11},
		 typePreferred: {name: 'foodIngredient', value: 21},
		 visitorID:48,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'Bloody Mary, Bloody Mary, Bloody Mary!',
		 name: 'Bloody Mary',
		 stateMultiplier:1.09,
		 tierMultiplier:1.08,
		 typeMultiplier:1.11,
		 weighting:1,
		 statePreferred: {name: 'White Enchant', value: 6},
		 tierPreferred: {name: 'silver', value: 8},
		 typePreferred: {name: 'gemPowder', value: 22},
		 visitorID:49,
	},
	{
		 adventuresAttempted:0,
		 adventuresCompleted:0,
		 desc: 'It\'s freezerin\' time!',
		 name: 'COLDBOT5000',
		 stateMultiplier:1.09,
		 tierMultiplier:1.13,
		 typeMultiplier:1.15,
		 weighting:6,
		 statePreferred: {name: 'Blue Enchant', value: 4},
		 tierPreferred: {name: 'rune', value: 6},
		 typePreferred: {name: 'hammer', value: 18},
		 visitorID:50,
	},
];
export default visitorTypes;
